// SPDX-License-Identifier: AGPL-3.0-only
//! Generate the `unitree_go` message types from the workspace `.msg` store.
//!
//! Reads every `examples/go2/schemas/unitree_go/msg/*.msg` and runs it through the
//! EXACT pipeline `native_ros2_messages`' own build script and the `dds_bridge`
//! generic codec run — `parse_rosmsg(text, <stem>, Some("unitree_go"))` →
//! `resolve_fixed_nested` → `generate_schema`. Sharing the pipeline is what
//! keeps the emitted `SCHEMA_HASH` byte-identical to the one the bridge stamps
//! into the frames it publishes; a divergence would show up as every frame
//! being dropped at the subscriber's schema-hash gate, not as a build error.
//!
//! Files are visited in SORTED order and the output is a single concatenation,
//! so the generated source is byte-identical across builds (Principle #7 —
//! codegen output ordering must be deterministic).

use cerulion_core::codegen::{generate_schema, parse_rosmsg, resolve_fixed_nested, MessageSchema};
use std::path::{Path, PathBuf};

/// The ROS package these `.msg` files belong to. It is the DIRECTORY name in
/// the store (`schemas/<pkg>/msg/`) and part of the schema hash input
/// (`pkg/Name`), so it must match what `dds_bridge`'s store scanner derives.
const PACKAGE: &str = "unitree_go";

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let msg_dir = Path::new(&manifest)
        .join("../../schemas")
        .join(PACKAGE)
        .join("msg");
    println!("cargo:rerun-if-changed={}", msg_dir.display());

    let mut files: Vec<PathBuf> = std::fs::read_dir(&msg_dir)
        .unwrap_or_else(|e| panic!("read the {PACKAGE} msg store {}: {e}", msg_dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("msg"))
        .collect();
    files.sort();
    assert!(
        !files.is_empty(),
        "the {PACKAGE} msg store {} holds no .msg files — this crate exists only to \
         generate them, so an empty store is a build error, never a silently empty crate",
        msg_dir.display()
    );

    let mut schemas: Vec<MessageSchema> = Vec::new();
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
        let stem = file
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("non-UTF-8 .msg file name: {}", file.display()));
        let text = std::fs::read_to_string(file)
            .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
        // A repo-controlled input that will not parse is always a bug: silently
        // skipping it would leave a node referencing a type that does not exist
        // (an unattributable "cannot find type" later) instead of naming the
        // file here.
        let schema = parse_rosmsg(&text, stem, Some(PACKAGE))
            .unwrap_or_else(|e| panic!("parse {}: {e}", file.display()));
        schemas.push(schema);
    }

    // Same resolution phase the codec runs, so nested-reference fixedness (and
    // therefore the wire layout AND the recipe-3 schema hash) is decided
    // identically on both sides. A warning here means a nested reference in the
    // store could not be resolved — that silently changes the parent's layout,
    // so fail rather than emit types that disagree with the bridge.
    let warnings = resolve_fixed_nested(&mut schemas);
    if !warnings.is_empty() {
        for w in &warnings {
            println!("cargo:warning=nested resolution: {w}");
        }
        panic!(
            "nested-schema resolution produced {} warning(s) over the {PACKAGE} store — \
             every reference must resolve cleanly or the generated types' wire layout \
             skews from the dds_bridge codec's (see the cargo warnings above)",
            warnings.len()
        );
    }

    let mut out = String::new();
    out.push_str("// Generated from examples/go2/schemas/unitree_go/msg/*.msg.\n");
    // NOTE: no inner attributes here — this file is `include!`d into the
    // middle of `src/lib.rs`, where an inner attribute is a hard error. The
    // crate-level allows live in `src/lib.rs` instead.
    out.push_str("// DO NOT EDIT - generated by examples/go2/lib/unitree_go/build.rs\n\n");
    for schema in &schemas {
        out.push_str(&format!("// === {} ===\n", schema.name));
        out.push_str(&generate_schema(schema));
        out.push('\n');
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("unitree_go.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
