"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class TestMessage(object):

    __slots__ = ["test_value"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.test_value = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(TestMessage._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.test_value))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TestMessage._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TestMessage._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = TestMessage()
        self.test_value = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if TestMessage in parents: return 0
        tmphash = (0x9adcd229345d2cdc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if TestMessage._packed_fingerprint is None:
            TestMessage._packed_fingerprint = struct.pack(">Q", TestMessage._get_hash_recursive([]))
        return TestMessage._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TestMessage._get_packed_fingerprint())[0]

