// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.0

#include <string.h>
#include "test_package_TestMessage.h"

static int __test_package_TestMessage_hash_computed;
static uint64_t __test_package_TestMessage_hash;

uint64_t __test_package_TestMessage_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __test_package_TestMessage_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __test_package_TestMessage_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x9adcd229345d2cdcLL
         + __int32_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __test_package_TestMessage_get_hash(void)
{
    if (!__test_package_TestMessage_hash_computed) {
        __test_package_TestMessage_hash = (int64_t)__test_package_TestMessage_hash_recursive(NULL);
        __test_package_TestMessage_hash_computed = 1;
    }

    return __test_package_TestMessage_hash;
}

int __test_package_TestMessage_encode_array(void *buf, int offset, int maxlen, const test_package_TestMessage *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].test_value), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int test_package_TestMessage_encode(void *buf, int offset, int maxlen, const test_package_TestMessage *p)
{
    int pos = 0, thislen;
    int64_t hash = __test_package_TestMessage_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __test_package_TestMessage_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __test_package_TestMessage_encoded_array_size(const test_package_TestMessage *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_t_encoded_array_size(&(p[element].test_value), 1);

    }
    return size;
}

int test_package_TestMessage_encoded_size(const test_package_TestMessage *p)
{
    return 8 + __test_package_TestMessage_encoded_array_size(p, 1);
}

int __test_package_TestMessage_decode_array(const void *buf, int offset, int maxlen, test_package_TestMessage *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].test_value), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __test_package_TestMessage_decode_array_cleanup(test_package_TestMessage *p, int elements)
{
    (void)p;
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_decode_array_cleanup(&(p[element].test_value), 1);

    }
    return 0;
}

int test_package_TestMessage_decode(const void *buf, int offset, int maxlen, test_package_TestMessage *p)
{
    int pos = 0, thislen;
    int64_t hash = __test_package_TestMessage_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __test_package_TestMessage_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int test_package_TestMessage_decode_cleanup(test_package_TestMessage *p)
{
    return __test_package_TestMessage_decode_array_cleanup(p, 1);
}

int __test_package_TestMessage_clone_array(const test_package_TestMessage *p, test_package_TestMessage *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_clone_array(&(p[element].test_value), &(q[element].test_value), 1);

    }
    return 0;
}

test_package_TestMessage *test_package_TestMessage_copy(const test_package_TestMessage *p)
{
    test_package_TestMessage *q = (test_package_TestMessage*) malloc(sizeof(test_package_TestMessage));
    __test_package_TestMessage_clone_array(p, q, 1);
    return q;
}

void test_package_TestMessage_destroy(test_package_TestMessage *p)
{
    __test_package_TestMessage_decode_array_cleanup(p, 1);
    free(p);
}

int test_package_TestMessage_publish(lcm_t *lc, const char *channel, const test_package_TestMessage *p)
{
      int max_data_size = test_package_TestMessage_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = test_package_TestMessage_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _test_package_TestMessage_subscription_t {
    test_package_TestMessage_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void test_package_TestMessage_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    test_package_TestMessage p;
    memset(&p, 0, sizeof(test_package_TestMessage));
    status = test_package_TestMessage_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding test_package_TestMessage!!!\n", status);
        return;
    }

    test_package_TestMessage_subscription_t *h = (test_package_TestMessage_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    test_package_TestMessage_decode_cleanup (&p);
}

test_package_TestMessage_subscription_t* test_package_TestMessage_subscribe (lcm_t *lcm,
                    const char *channel,
                    test_package_TestMessage_handler_t f, void *userdata)
{
    test_package_TestMessage_subscription_t *n = (test_package_TestMessage_subscription_t*)
                       malloc(sizeof(test_package_TestMessage_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 test_package_TestMessage_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg test_package_TestMessage LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int test_package_TestMessage_subscription_set_queue_capacity (test_package_TestMessage_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int test_package_TestMessage_unsubscribe(lcm_t *lcm, test_package_TestMessage_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe test_package_TestMessage_handler %p!\n", (void*)hid);
        return -1;
    }
    free (hid);
    return 0;
}

