// SPDX-License-Identifier: AGPL-3.0-only
//! Checkpoint state capture and restore across the cdylib
//! wall, driven over a real `dlopen` through `DylibNodeEntry`.
//!
//! # What this guards against
//!
//! Every `#[cerulion_node]` struct carries an `impl CerulionState`
//! and the runtime has a restore seam — but the two must be joined for
//! the SHIPPING node form. A `graph run` loads cdylibs; if `DylibNodeEntry`
//! inherited `NodeEntry`'s defaults, every cdylib node would declare **no**
//! restorable state and `restore_node_states` would skip it: a recorded anchor
//! offered and silently dropped, the node resuming from its constructor.
//!
//! # What is asserted here, and against what
//!
//! Every payload oracle is **hand-built from the documented encoding** (see
//! `cerulion_core::state`'s module table) — never a re-capture compared with
//! itself:
//!
//! | field | bytes |
//! |---|---|
//! | `counter: u64` | 8 LE |
//! | `label: String` | `u32` LE byte length + UTF-8 |
//! | `history: Vec<f64>` | `u32` LE count + each `f64`'s LE bit pattern |
//! | `tags: HashMap<u32, u8>` | `u32` LE count + sorted `(key, value)` pairs |
//! | `handle: u64` (`#[cerulion(reconstruct)]`) | **none** |
//!
//! The `#[output]` port contributes nothing, and that is asserted rather than
//! assumed: a walk that included it would not compile at all, but a walk that
//! included the ESCAPED field would compile and quietly clobber a handle the
//! node re-derived in `init()`.
//!
//! # The refuse-on-uncovered pin
//!
//! A cdylib WITHOUT the exports — every hand-written raw-FFI node, every older
//! build — must REFUSE at the restore path naming the node and the fix. It must
//! never report success while leaving the node at `Default`, because a resumed
//! run would then produce a confident divergence report about an execution that
//! never happened. Pinned by
//! `a_symbol_less_cdylib_declares_no_state_and_refuses_a_restore_naming_the_node_and_the_fix`
//! over the real raw-FFI `test_node_cdylib`.
//!
//! # The misreporting-exporter pin (a return code is a CLAIM, not the verdict)
//!
//! The three state symbols are ADDITIVE and resolved BY NAME, so nothing tells the
//! host that the exporter behind them was generated by `#[cerulion_node]`. A
//! hand-written raw-FFI exporter may ignore the sink callback's non-zero
//! return, keep streaming, and still report 0 — and a host that believes that 0
//! accepts whatever prefix its own sink took as the node's WHOLE state. Pinned
//! by the `..._even_though_the_cdylib_reported_success` pair over
//! `test_node_state_liar_cdylib`, a real hand-written cdylib built for exactly
//! this: no macro fixture can reproduce it, because the generated exporter is
//! correct by construction.
//!
//! # Running (cdylib `NODES` singleton + iceoryx2 SHM → serial)
//!
//! ```bash
//! cargo build -p test_node_macro_state_cdylib -p test_node_cdylib \
//!             -p test_node_state_liar_cdylib
//! cargo test -p cerulion_core --test cdylib_state_ffi_test -- --test-threads=1
//! ```

use std::sync::{Arc, Mutex};
use std::time::Duration;

use cerulion_core::clock::VirtualClock;
use cerulion_core::graph::config::{GraphConfig, InputDef, NodeDef, OutputDef};
use cerulion_core::graph::node::{
    ClosureNodeEntry, DylibNodeEntry, MacroPolicy, NodeEntry, NodeInfo,
};
use cerulion_core::graph::GraphRuntime;
use cerulion_core::prelude::*;
use cerulion_core::state::{BoundedSink, CerulionState, VecSink};
use cerulion_core::state_restore::AnchorBlob;
use indexmap::IndexMap;
use serial_test::serial;

// ===========================================================================
// the in-process twins
// ===========================================================================

/// A twin of the cdylib fixture's struct, declared field-for-field and NAMED
/// identically (the shape folds the type name, so a differently-named twin
/// would prove nothing).
///
/// Its `tick` body is DELIBERATELY different from the fixture's. That is the
/// shape contract's first half made testable: a tick-logic edit is not a shape
/// edit, so a recording keeps restoring across one.
mod twin {
    use std::collections::HashMap;

    use cerulion_core::prelude::*;
    use native_ros2_messages::geometry_msgs::Quaternion;

    #[cerulion_node(period_ms = 10)]
    pub struct StateProbeNode {
        #[output]
        pub out: Quaternion,
        pub counter: u64,
        pub label: String,
        pub history: Vec<f64>,
        pub tags: HashMap<u32, u8>,
        #[cerulion(reconstruct)]
        pub handle: u64,
    }

    #[cerulion_node_impl]
    impl StateProbeNode {
        fn tick(&mut self) -> Result<(), NodeError> {
            // Deliberately NOT the fixture's body: different arithmetic, same
            // fields. The shape must not notice.
            self.out.x = (self.counter * 2) as f64;
            self.out.y = self.history.iter().sum::<f64>();
            self.out.z = self.label.len() as f64;
            self.out.w = (self.handle + self.tags.len() as u64) as f64;
            self.counter += 3;
            Ok(())
        }
    }
}

/// The same struct with ONE field RETYPED (`counter: u64` → `u32`).
///
/// The shape contract's second half: a struct-shape edit invalidates the anchor,
/// and it must be refused rather than decoded as a prefix.
mod skewed {
    use std::collections::HashMap;

    use cerulion_core::prelude::*;
    use native_ros2_messages::geometry_msgs::Quaternion;

    #[cerulion_node(period_ms = 10)]
    pub struct StateProbeNode {
        #[output]
        pub out: Quaternion,
        pub counter: u32,
        pub label: String,
        pub history: Vec<f64>,
        pub tags: HashMap<u32, u8>,
        #[cerulion(reconstruct)]
        pub handle: u64,
    }

    #[cerulion_node_impl]
    impl StateProbeNode {
        fn tick(&mut self) -> Result<(), NodeError> {
            self.out.x = self.counter as f64;
            self.out.y = self.history.len() as f64;
            self.out.z = self.label.len() as f64;
            self.out.w = (self.handle + self.tags.len() as u64) as f64;
            self.counter += 1;
            Ok(())
        }
    }
}

// ===========================================================================
// hand oracles
// ===========================================================================

/// The documented encoding of the fixture's three CAPTURED fields, in
/// declaration order. Written out by hand rather than produced by the encoder,
/// so an assertion against it is a cross-check and not a self-compare.
fn hand_payload(counter: u64, label: &str, history: &[f64], tags: &[(u32, u8)]) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend_from_slice(&counter.to_le_bytes());
    out.extend_from_slice(&(label.len() as u32).to_le_bytes());
    out.extend_from_slice(label.as_bytes());
    out.extend_from_slice(&(history.len() as u32).to_le_bytes());
    for f in history {
        out.extend_from_slice(&f.to_le_bytes());
    }
    // A hash-like container emits in SORTED key order, so a `HashMap`'s
    // per-process iteration order never reaches a recording. `tags` is passed
    // already sorted; the oracle does not sort it, so a capture that emitted in
    // iteration order would have to be lucky to pass.
    out.extend_from_slice(&(tags.len() as u32).to_le_bytes());
    for (k, v) in tags {
        out.extend_from_slice(&k.to_le_bytes());
        out.extend_from_slice(&v.to_le_bytes());
    }
    out
}

/// The bytes of everything BEFORE the hash-like field, which is where a capture
/// into a too-small sink must stop when the bound crossed the FFI.
fn hand_payload_before_tags(counter: u64, label: &str, history: &[f64]) -> Vec<u8> {
    let full = hand_payload(counter, label, history, &[]);
    full[..full.len() - 4].to_vec()
}

/// Frame a payload the way a recorded anchor is framed. The FRAMING comes from
/// production code (`AnchorBlob::write_header`) because that is the half the
/// runtime decodes; only the payload is hand-built.
fn framed(shape: u64, payload: &[u8]) -> Vec<u8> {
    let mut sink = VecSink::new();
    AnchorBlob::write_header(shape, &mut sink).expect("framing fits a Vec");
    let mut blob = sink.into_inner();
    blob.extend_from_slice(payload);
    blob
}

// ===========================================================================
// fixtures + harness
// ===========================================================================

/// Where cargo put the fixture cdylibs.
///
/// Honours `CARGO_TARGET_DIR` before falling back to `<workspace>/target`: the
/// sibling cdylib tests hardcode the latter, which silently stops finding
/// fixtures the moment anyone builds with a shared target directory.
fn target_dir() -> std::path::PathBuf {
    if let Ok(dir) = std::env::var("CARGO_TARGET_DIR") {
        if !dir.is_empty() {
            return std::path::PathBuf::from(dir);
        }
    }
    let mut path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop(); // up from crates/cerulion_core to crates/
    path.pop(); // up from crates/ to the workspace root
    path.push("target");
    path
}

fn find_cdylib(crate_name: &str) -> std::path::PathBuf {
    let mut path = target_dir();
    path.push("debug");
    #[cfg(target_os = "macos")]
    path.push(format!("lib{crate_name}.dylib"));
    #[cfg(target_os = "linux")]
    path.push(format!("lib{crate_name}.so"));
    #[cfg(target_os = "windows")]
    path.push(format!("{crate_name}.dll"));
    assert!(
        path.exists(),
        "test cdylib not found at {path:?}. Run `cargo build -p {crate_name}` first."
    );
    path
}

fn state_cdylib() -> std::path::PathBuf {
    find_cdylib("test_node_macro_state_cdylib")
}

/// The raw-FFI cdylib — hand-written, exports none of the state symbols. THE
/// uncovered population.
fn symbol_less_cdylib() -> std::path::PathBuf {
    find_cdylib("test_node_cdylib")
}

fn prefix_for(tag: &str) -> String {
    format!(
        "d6_{tag}_{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("clock")
            .as_nanos()
    )
}

/// One `probe` (the cdylib under test) publishing into one recording `sink`.
fn probe_graph(prefix: &str) -> GraphConfig {
    GraphConfig {
        level_assignments: None,
        network: None,
        process_groups: Default::default(),
        process_group_order: Default::default(),
        multi_publisher_topics: Vec::new(),
        name: None,
        identity: "d6".to_string(),
        prefix: prefix.to_string(),
        nodes: vec![
            NodeDef {
                ros2: None,
                id: "probe".to_string(),
                node_type: "probe".to_string(),
                inputs: vec![],
                outputs: vec![OutputDef {
                    name: "out".to_string(),
                    schema: "Quaternion".to_string(),
                    max_slice_len: None,
                    history_size: 0,
                    topic: None,
                }],
            },
            NodeDef {
                ros2: None,
                id: "sink".to_string(),
                node_type: "sink".to_string(),
                inputs: vec![InputDef {
                    name: "inp".to_string(),
                    source: "probe/out".to_string(),
                }],
                outputs: vec![],
            },
        ],
    }
}

type Seen = Arc<Mutex<Vec<(u64, u64, u64, u64)>>>;

fn build(prefix: &str, probe: Box<dyn NodeEntry>, seen: Seen) -> TransportResult<GraphRuntime> {
    let mut factories: IndexMap<String, Box<dyn NodeEntry>> = IndexMap::new();
    factories.insert("probe".to_string(), probe);

    let info = NodeInfo::from_names(vec!["inp".to_string()], vec![])
        .with_policy(MacroPolicy::Period { period_ms: 10 });
    let sink = ClosureNodeEntry::new(info, move |ctx| {
        let sub = ctx.subscriber("inp").expect("sink subscriber wired");
        let mut batch = Vec::new();
        let _ = sub.try_receive(|msg| {
            let p = msg.payload();
            let at = |i: usize| f64::from_le_bytes(p[i..i + 8].try_into().expect("8 bytes")) as u64;
            batch.push((at(0), at(8), at(16), at(24)));
        })?;
        seen.lock().expect("seen").extend(batch);
        Ok(())
    })
    .with_label("sink")
    .with_unified_drain(false);
    factories.insert("sink".to_string(), Box::new(sink));

    GraphRuntime::build_for_test(
        probe_graph(prefix),
        factories,
        Arc::new(VirtualClock::new()),
        16,
    )
}

/// Build a graph around the state cdylib and hand back the runtime plus a
/// clone of the `probe` entry, so a test can drive the FFI directly on the
/// SAME initialized instance the runtime holds.
fn built_probe(tag: &str) -> (GraphRuntime, Arc<Mutex<Box<dyn NodeEntry>>>, Seen) {
    let seen: Seen = Arc::new(Mutex::new(Vec::new()));
    let prefix = prefix_for(tag);
    let entry = DylibNodeEntry::load(&state_cdylib()).expect("state cdylib loads");
    let runtime = build(&prefix, Box::new(entry), Arc::clone(&seen)).expect("graph builds");
    let probe = runtime
        .node_entry_arc_for_test("probe")
        .expect("probe is in the node map");
    (runtime, probe, seen)
}

// ===========================================================================
// the capture half
// ===========================================================================

#[test]
#[serial]
fn a_fresh_cdylib_nodes_capture_is_the_hand_built_default_encoding_and_its_port_contributes_nothing(
) {
    let (_runtime, probe, _seen) = built_probe("cap");

    let mut sink = VecSink::new();
    probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect("a macro cdylib can capture");
    let captured = sink.into_inner();

    // A freshly constructed node: counter 0, empty label, empty history. The
    // `#[cerulion(reconstruct)]` handle is 7 after `init` and contributes
    // NOTHING, which the byte length proves — 8 + 4 + 0 + 4 + 4 = 20 bytes, with
    // no room for a fifth field and none for the `Quaternion` port's 32.
    assert_eq!(captured, hand_payload(0, "", &[], &[]));
    assert_eq!(captured.len(), 20, "captured: {captured:?}");
}

#[test]
#[serial]
fn a_capture_into_a_sink_too_small_reports_the_hosts_bound_not_a_broken_node() {
    let (_runtime, probe, _seen) = built_probe("small");

    // Four bytes cannot hold the leading `u64`, so the very first write refuses.
    let mut arena = [0u8; 4];
    let mut sink = BoundedSink::new(&mut arena);
    let err = probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect_err("a 4-byte arena cannot take a u64");
    let text = err.to_string();
    assert!(
        text.contains("its buffer is too small"),
        "must blame the HOST's bound, not the node: {text}"
    );
    assert!(
        text.contains("probe") || text.contains("test_node_macro_state_cdylib"),
        "must name the node: {text}"
    );
}

#[test]
#[serial]
fn a_hash_like_container_refuses_before_building_its_sort_index_because_the_bound_crossed_the_wall()
{
    // WHY THIS ARM EXISTS. `capacity_hint` is the caller's bound carried across
    // the FFI as a scalar, because a callback ABI has nowhere else to put it.
    // Drop it and nothing about the VERDICT changes — the host's sink still
    // refuses, so the capture still fails — and the cost is invisible: the
    // cdylib builds a `Vec<&K>` sort index over the WHOLE container before
    // discovering the sink cannot take it (the ~240 MB-on-the-node-thread
    // case). One consequence IS observable, and it is what this arm reads: with
    // the bound, `guard_sort_scratch` calls `refuse()` and returns BEFORE the
    // container's four-byte count prefix is written; without it, that prefix
    // lands.
    let (_runtime, probe, _seen) = built_probe("hint");

    // Give the node a two-entry map. Its floor is 2 * (4 + 1) + 4 = 14 bytes,
    // so a sink with 4 bytes left provably cannot take it.
    probe
        .lock()
        .expect("probe")
        .restore_state(&hand_payload(1, "ab", &[], &[(1, 10), (2, 20)]))
        .expect("restore the map");

    let before_tags = hand_payload_before_tags(1, "ab", &[]);
    let mut arena = vec![0u8; before_tags.len() + 4];
    let mut sink = BoundedSink::new(&mut arena);
    let err = probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect_err("the map cannot fit");
    assert!(
        err.to_string().contains("its buffer is too small"),
        "the host's bound, not a broken node: {err}"
    );
    assert_eq!(
        sink.len(),
        before_tags.len(),
        "the count prefix must NOT have been written: the container refused \
         before it built an index, which is only possible if the bound crossed \
         the FFI"
    );
    assert_eq!(&arena[..before_tags.len()], &before_tags[..]);
}

// ===========================================================================
// the restore half
// ===========================================================================

#[test]
#[serial]
fn a_hand_built_anchor_restores_and_re_captures_byte_identical() {
    let (_runtime, probe, _seen) = built_probe("rt");

    let want = hand_payload(100, "resumed-state", &[1.5, 2.5, 3.5], &[(1, 10), (2, 20)]);
    probe
        .lock()
        .expect("probe")
        .restore_state(&want)
        .expect("a hand-built payload restores");

    let mut sink = VecSink::new();
    probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect("re-capture");
    // Byte-identical to what went IN — the round trip closes on the hand
    // oracle at both ends, so neither half is compared against itself.
    assert_eq!(sink.into_inner(), want);
}

#[test]
#[serial]
fn a_trailing_byte_in_the_payload_refuses_rather_than_decoding_a_prefix() {
    let (_runtime, probe, _seen) = built_probe("trail");

    let mut blob = hand_payload(5, "x", &[], &[]);
    blob.push(0xAB); // one byte the running field list does not account for
    let err = probe
        .lock()
        .expect("probe")
        .restore_state(&blob)
        .expect_err("a trailing byte is a drift signal, not padding");
    let text = err.to_string();
    assert!(
        text.contains("trailing") || text.contains("Trailing"),
        "names the condition: {text}"
    );
    assert!(
        text.contains("PARTIALLY restored"),
        "says the run must fail rather than continue: {text}"
    );
}

#[test]
#[serial]
fn a_restored_value_reaches_the_cdylibs_own_tick_and_its_reconstruct_field_survives() {
    // The CONTROL first: the same graph with NO restore, so every moved number
    // below is attributable to the restore rather than to the fixture.
    let (mut control, _probe, control_seen) = built_probe("beh_ctl");
    // THREE steps for TWO deliveries: the sink drains one level behind the
    // probe's publish, so the last step's frame is still in flight.
    for _ in 0..3 {
        control.step(Duration::from_millis(10));
    }
    assert_eq!(
        control_seen.lock().expect("seen").clone(),
        // counter 0 then 1; empty history; empty label; `handle` = 7 from
        // `init()`, which the constructor's `Default` would have left at 0.
        vec![(0, 0, 0, 7), (1, 0, 0, 7)],
        "the un-restored control"
    );
    drop(control);

    let (mut runtime, _probe, seen) = built_probe("beh");
    let shape = {
        let guard = runtime
            .node_entry_arc_for_test("probe")
            .expect("probe entry");
        let guard = guard.lock().expect("probe");
        guard
            .state_shape()
            .expect("a macro cdylib declares a shape")
    };

    let mut anchors = std::collections::BTreeMap::new();
    anchors.insert(
        "probe".to_string(),
        framed(
            shape,
            &hand_payload(100, "resumed-state", &[1.5, 2.5, 3.5], &[(1, 10), (2, 20)]),
        ),
    );
    let report = runtime
        .restore_node_states(&anchors)
        .expect("the anchor applies");
    assert_eq!(report.restored, vec!["probe".to_string()]);
    assert!(report.declared_no_state.is_empty());

    for _ in 0..3 {
        runtime.step(Duration::from_millis(10));
    }
    assert_eq!(
        seen.lock().expect("seen").clone(),
        // counter resumed at 100 then 101; history length 3; label length 13;
        // and `handle + tags.len()` = 7 + 2 = 9 — the recording carried nothing
        // for `handle`, so a restore that clobbered it would read 2 here.
        vec![(100, 3, 13, 9), (101, 3, 13, 9)],
    );
}

// ===========================================================================
// THE REFUSE-ON-UNCOVERED PIN
// ===========================================================================

#[test]
#[serial]
fn a_symbol_less_cdylib_declares_no_state_and_refuses_a_restore_naming_the_node_and_the_fix() {
    // The raw-FFI fixture: a real, hand-written cdylib that loads fine and
    // exports none of the three state symbols.
    let mut entry = DylibNodeEntry::load(&symbol_less_cdylib())
        .expect("a symbol-less cdylib must still LOAD (the exports are additive)");

    // (a) It declares NO state, so `restore_node_states` reports it under
    //     `declared_no_state` instead of applying anything.
    assert_eq!(entry.state_shape(), None);

    // (b) And reaching the restore path directly REFUSES. Never `Ok(())`: that
    //     would leave the node at its constructor's `Default` while the caller
    //     recorded it as restored.
    let err = entry
        .restore_state(&hand_payload(1, "x", &[], &[]))
        .expect_err("an uncovered cdylib must refuse a recorded anchor");
    let text = err.to_string();
    assert!(
        text.contains("declares no restorable state"),
        "names the condition: {text}"
    );
    assert!(
        text.contains("test_node_cdylib"),
        "names the offending node: {text}"
    );
    assert!(
        text.contains("cerulion_node_restore_state") && text.contains("#[cerulion_node]"),
        "names the fix: {text}"
    );
    assert!(
        text.contains("resume from its constructor's defaults"),
        "says what silence would have cost: {text}"
    );

    // (c) The capture half refuses too — an anchor that captured nothing is
    //     worse than no anchor, because a resume would apply that emptiness.
    let mut sink = VecSink::new();
    let err = entry
        .capture_state(&mut sink)
        .expect_err("an uncovered cdylib must refuse to capture");
    assert!(
        err.to_string().contains("declares no capturable state"),
        "names the condition: {err}"
    );
    assert!(sink.is_empty(), "and wrote nothing");
}

#[test]
#[serial]
fn an_uninitialized_cdylib_still_declares_its_shape_but_refuses_to_capture_or_restore() {
    // The shape is a const of the TYPE, so it is answerable before `init()` —
    // which is what stops a not-yet-initialized node from claiming it has no
    // state and being skipped by the restore.
    let mut entry = DylibNodeEntry::load(&state_cdylib()).expect("state cdylib loads");
    assert_eq!(
        entry.state_shape(),
        Some(<twin::StateProbeNode as CerulionState>::STATE_SHAPE),
        "the shape is readable at load, with no handle and no init"
    );

    let mut sink = VecSink::new();
    let err = entry
        .capture_state(&mut sink)
        .expect_err("no instance exists yet");
    assert!(
        err.to_string().contains("has not been initialized"),
        "{err}"
    );

    let err = entry
        .restore_state(&hand_payload(1, "", &[], &[]))
        .expect_err("no instance exists yet");
    assert!(
        err.to_string().contains("has not been initialized"),
        "{err}"
    );
}

// ===========================================================================
// shape: the shape contract, and in-process parity
// ===========================================================================

#[test]
#[serial]
fn a_tick_logic_edit_keeps_the_shape_while_a_field_retype_moves_it() {
    let entry = DylibNodeEntry::load(&state_cdylib()).expect("state cdylib loads");
    let cdylib_shape = entry.state_shape().expect("declares a shape");

    // Read through the production `NodeEntry` seam on both twins, not off the
    // associated const: the const is what the seam RETURNS, and a test that
    // reads it directly cannot see a seam that stopped returning it.
    let twin_shape = twin::StateProbeNodeEntry::new()
        .state_shape()
        .expect("the twin declares a shape");
    let skewed_shape = skewed::StateProbeNodeEntry::new()
        .state_shape()
        .expect("the skewed twin declares a shape");

    // Same struct, DIFFERENT tick body → same shape. A recording keeps
    // restoring across a logic edit.
    assert_eq!(
        cdylib_shape, twin_shape,
        "a tick-logic edit is not a shape edit"
    );

    // One field RETYPED → a different shape, so the anchor is invalidated.
    assert_ne!(
        cdylib_shape, skewed_shape,
        "retyping `counter` u64 -> u32 must move the shape"
    );
}

#[test]
#[serial]
fn a_shape_mismatch_refuses_before_a_byte_is_applied() {
    let (runtime, probe, _seen) = built_probe("skew");

    // A blob framed with the SKEWED type's shape — what a recording made
    // before a struct-shape edit looks like afterwards.
    let skewed_shape = skewed::StateProbeNodeEntry::new()
        .state_shape()
        .expect("the skewed twin declares a shape");
    let mut anchors = std::collections::BTreeMap::new();
    anchors.insert(
        "probe".to_string(),
        framed(
            skewed_shape,
            &hand_payload(100, "resumed-state", &[1.5], &[]),
        ),
    );
    let err = runtime
        .restore_node_states(&anchors)
        .expect_err("a shape mismatch is terminal");
    let text = err.to_string();
    assert!(text.contains("probe"), "names the offending node: {text}");

    // And nothing was applied: the node still captures its DEFAULT encoding.
    let mut sink = VecSink::new();
    probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect("capture");
    assert_eq!(sink.into_inner(), hand_payload(0, "", &[], &[]));
}

#[test]
#[serial]
fn the_cdylib_and_an_in_process_twin_agree_on_shape_and_on_bytes() {
    // The divergence class: the two forms run the SAME generated
    // `cer_capture`, so a cdylib's anchor and an in-process one must be
    // interchangeable. Asserted on BOTH halves — the identity the restore
    // checks, and the bytes it applies.
    let (_runtime, probe, _seen) = built_probe("parity");

    let mut cdylib_sink = VecSink::new();
    probe
        .lock()
        .expect("probe")
        .capture_state(&mut cdylib_sink)
        .expect("cdylib capture");

    let mut in_process = twin::StateProbeNodeEntry::new();
    let mut twin_sink = VecSink::new();
    in_process
        .capture_state(&mut twin_sink)
        .expect("in-process capture");

    assert_eq!(
        probe.lock().expect("probe").state_shape(),
        in_process.state_shape(),
        "the two forms must agree on the identity a restore checks"
    );
    assert_eq!(
        cdylib_sink.into_inner(),
        twin_sink.into_inner(),
        "and on the bytes it applies"
    );

    // The in-process form takes the same payload, through the same seam.
    let want = hand_payload(100, "resumed-state", &[1.5, 2.5, 3.5], &[(1, 10), (2, 20)]);
    in_process.restore_state(&want).expect("in-process restore");
    let mut after = VecSink::new();
    in_process.capture_state(&mut after).expect("re-capture");
    assert_eq!(after.into_inner(), want);
}

// ===========================================================================
// THE MISREPORTING-EXPORTER PIN: a return code is a CLAIM, not the verdict
// ===========================================================================
//
// The three state symbols are ADDITIVE and resolved BY NAME, so nothing tells the
// host that the exporter behind them came out of `#[cerulion_node]`. The
// generated one maps a refused chunk onto `-6`; a HAND-WRITTEN raw-FFI one (the
// population `test_node_cdylib` next door already proves exists) is free to
// ignore the callback's non-zero return, keep streaming, and still report 0.
//
// If the host believes that 0, it accepts whatever prefix its own sink managed
// to take as this node's WHOLE state. A truncated anchor is not a loud failure:
// it is a recording that restores later as if it were complete, so the resumed
// node runs on state nobody captured while the run reports it `restored`
// (Principle #6 — a missing frame must not be lost silently; Principle #13 —
// nothing fabricated).
//
// These arms drive the real misbehaviour over a real `dlopen`
// (`test_node_state_liar_cdylib`), because every macro fixture in the tree is
// incapable of producing it by construction.

/// This fixture's declared `STATE_SHAPE`, spelled out by hand — the same
/// literal the fixture declares, written independently here so the assertion is
/// a cross-check rather than a read-back.
const LIAR_SHAPE: u64 = 0x1053_D600_5A1E_0001;

/// The liar fixture's documented payload: `counter` LE, then the label, then
/// the tail marker. Hand-built from the fixture's own module table.
fn liar_payload(counter: u64) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend_from_slice(&counter.to_le_bytes());
    out.extend_from_slice(b"liar_fixture");
    out.extend_from_slice(&0xDEAD_BEEFu32.to_le_bytes());
    out
}

/// The hand-written raw-FFI cdylib whose exporter can be told to lie.
fn liar_cdylib() -> std::path::PathBuf {
    find_cdylib("test_node_state_liar_cdylib")
}

/// Panic-safe process-env switch for the fixture's mode (the whole file is
/// `#[serial]`, so the process env is exclusively ours for the test's body).
struct ModeGuard;

impl ModeGuard {
    fn set(mode: &str) -> Self {
        std::env::set_var("STATE_CAPTURE_MODE", mode);
        Self
    }
}

impl Drop for ModeGuard {
    fn drop(&mut self) {
        std::env::remove_var("STATE_CAPTURE_MODE");
    }
}

/// Load the liar fixture and `init` it, so it holds a live instance the capture
/// path can reach. It declares no ports, so an empty test context is the whole
/// requirement.
fn init_liar() -> DylibNodeEntry {
    let mut entry = DylibNodeEntry::load(&liar_cdylib()).expect("the liar cdylib loads");
    entry
        .init(cerulion_core::graph::node::NodeContext::for_tests(
            IndexMap::new(),
            IndexMap::new(),
        ))
        .expect("the liar cdylib inits");
    entry
}

/// A sink that records EVERY chunk it was offered — including the ones it
/// refused — so a test can tell "the exporter stopped" from "the exporter kept
/// going". `BoundedSink` cannot: a refused write leaves no trace of its size.
struct RecordingSink {
    cap: usize,
    accepted: Vec<u8>,
    /// One entry per `write` call: the chunk's length and whether it was taken.
    offers: Vec<(usize, bool)>,
    refused: bool,
}

impl RecordingSink {
    fn new(cap: usize) -> Self {
        Self {
            cap,
            accepted: Vec::new(),
            offers: Vec::new(),
            refused: false,
        }
    }
}

impl cerulion_core::state::StateSink for RecordingSink {
    fn write(&mut self, bytes: &[u8]) -> Result<(), cerulion_core::state::SinkFull> {
        // Latches exactly like `BoundedSink`: a small write landing after a
        // refused large one would leave a hole in the middle of an encoding
        // that still looks structurally valid.
        if self.refused || self.accepted.len() + bytes.len() > self.cap {
            self.offers.push((bytes.len(), false));
            self.refused = true;
            return Err(cerulion_core::state::SinkFull);
        }
        self.accepted.extend_from_slice(bytes);
        self.offers.push((bytes.len(), true));
        Ok(())
    }

    fn refuse(&mut self) {
        self.refused = true;
    }
}

/// A sink that UNWINDS on its first write — the other way a host sink can fail
/// a chunk. The trampoline catches it (an `extern "C"` unwind would abort the
/// process), so the cdylib sees only a non-zero return, exactly as for a
/// refusal.
struct PanickingSink {
    calls: usize,
}

impl cerulion_core::state::StateSink for PanickingSink {
    fn write(&mut self, _bytes: &[u8]) -> Result<(), cerulion_core::state::SinkFull> {
        self.calls += 1;
        panic!("this host sink is broken");
    }
}

#[test]
#[serial]
fn a_capture_the_host_sink_refused_is_refused_even_though_the_cdylib_reported_success() {
    let _mode = ModeGuard::set("liar");
    let entry = init_liar();

    // The fixture declares a shape, so the host treats it as a covered node —
    // the capture path is genuinely reached rather than short-circuited by the
    // uncovered refusal.
    assert_eq!(entry.state_shape(), Some(LIAR_SHAPE));

    // Eight bytes take the first chunk (the counter) and nothing else: the second is 12
    // bytes and the third is 4, so both are refused.
    let mut sink = RecordingSink::new(8);
    let err = entry
        .capture_state(&mut sink)
        .expect_err("a capture the host's sink refused is not a capture");

    // (a) The exporter really did misbehave — otherwise this arm would be
    //     pinning nothing. It was refused and STILL offered every later chunk.
    assert_eq!(
        sink.offers,
        vec![(8, true), (12, false), (4, false)],
        "the fixture must have kept streaming past a refusal: {:?}",
        sink.offers
    );

    // (b) The prefix that reached the sink is a STRICT prefix of this node's
    //     state and carries none of the tail marker. Accepting it would have
    //     written that as a complete anchor.
    let whole = liar_payload(0);
    assert_eq!(sink.accepted, whole[..8].to_vec());
    assert!(
        !sink
            .accepted
            .windows(4)
            .any(|w| w == 0xDEAD_BEEFu32.to_le_bytes()),
        "the truncated prefix must not carry the tail marker"
    );

    // (c) The diagnostic names the node, the condition, and WHOSE fault it is.
    //     "buffer too small" alone would be wrong here: a conforming exporter
    //     of the same node would have said so itself, and the actionable fact
    //     is that this one did not.
    let text = err.to_string();
    assert!(
        text.contains("test_node_state_liar_cdylib"),
        "names the offending node: {text}"
    );
    assert!(
        text.contains("REFUSED"),
        "names the condition the host observed: {text}"
    );
    assert!(
        text.contains("returned 0"),
        "says the cdylib claimed success: {text}"
    );
    assert!(
        text.contains("exporter is BROKEN"),
        "blames the exporter, not the buffer: {text}"
    );
    assert!(
        text.contains("-6"),
        "names the code the exporter owed us: {text}"
    );
    // (c2) And whatever the cdylib left in its FFI error slot is SURFACED, not
    //      thrown away: it is the only thing the exporter had to say about a
    //      capture it got wrong. (Draining it is also what stops it resurfacing
    //      against a later, unrelated failure — the slot is process-global for
    //      the life of the loaded library.)
    assert!(
        text.contains("ignored 2 sink rejection(s) and reported success"),
        "surfaces the cdylib's own message: {text}"
    );

    // (d) And the host's own sink is latched, so nothing downstream can read
    //     its prefix back as accepted bytes.
    assert!(sink.refused, "the caller's sink must be left refused");
}

#[test]
#[serial]
fn a_capture_the_host_sink_panicked_on_is_refused_even_though_the_cdylib_reported_success() {
    let _mode = ModeGuard::set("liar");
    let entry = init_liar();

    let mut sink = PanickingSink { calls: 0 };
    let err = entry
        .capture_state(&mut sink)
        .expect_err("a capture whose sink unwound is not a capture");

    // The exporter ignored all three non-zero returns, so the process survived
    // three caught unwinds — the trampoline's `catch_unwind` is what makes that
    // an error rather than an abort.
    assert_eq!(sink.calls, 3, "the fixture kept streaming past the panics");
    let text = err.to_string();
    assert!(
        text.contains("test_node_state_liar_cdylib"),
        "names the offending node: {text}"
    );
    assert!(
        text.contains("PANICKED"),
        "a broken sink and a small buffer are opposite diagnoses: {text}"
    );
    assert!(
        text.contains("returned 0"),
        "says the cdylib claimed success: {text}"
    );
}

/// A sink that reports whether the HOST latched it, so "was `refuse()` called"
/// is observable through the production `StateSink` API rather than inferred
/// from a re-implementation of `BoundedSink`'s accounting.
///
/// One type serves both halves of the discrimination: `panic_at` makes it
/// unwind on the n-th write (a BROKEN sink), `cap` makes it fill (an EXHAUSTED
/// one). The two must be charged differently, and nothing but this counter can
/// tell them apart from outside.
struct LatchSpySink {
    cap: usize,
    panic_at: Option<usize>,
    writes: usize,
    accepted: usize,
    returned_full: bool,
    refuse_calls: usize,
}

impl LatchSpySink {
    fn panicking(panic_at: usize) -> Self {
        Self {
            // Ample: this sink must be observably NOT full when it unwinds, or
            // the arm could not tell the two conditions apart.
            cap: usize::MAX,
            panic_at: Some(panic_at),
            writes: 0,
            accepted: 0,
            returned_full: false,
            refuse_calls: 0,
        }
    }

    fn bounded(cap: usize) -> Self {
        Self {
            cap,
            panic_at: None,
            writes: 0,
            accepted: 0,
            returned_full: false,
            refuse_calls: 0,
        }
    }
}

impl cerulion_core::state::StateSink for LatchSpySink {
    fn write(&mut self, bytes: &[u8]) -> Result<(), cerulion_core::state::SinkFull> {
        self.writes += 1;
        if self.panic_at == Some(self.writes) {
            panic!("this host sink is broken");
        }
        if self.returned_full || self.accepted + bytes.len() > self.cap {
            self.returned_full = true;
            return Err(cerulion_core::state::SinkFull);
        }
        self.accepted += bytes.len();
        Ok(())
    }

    fn refuse(&mut self) {
        self.refuse_calls += 1;
    }
}

#[test]
#[serial]
fn a_sink_that_unwound_is_not_latched_as_a_sink_that_filled() {
    // Driven through the MACRO fixture, so the exporter under test is the
    // GENERATED one — and the generated `__CerFfiStateSink::write` maps EVERY
    // non-zero callback return onto `SinkFull`, panic included. The cdylib
    // therefore reports -6 ("the host sink refused") for a sink that did not
    // refuse anything; only the host's own bridge knows it unwound.
    let (_runtime, probe, _seen) = built_probe("latchpanic");

    let mut sink = LatchSpySink::panicking(1);
    let err = probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect_err("a capture whose sink unwound is not a capture");

    // The apparatus really produced the condition: the sink unwound, and it was
    // NOT full — it never once returned `SinkFull`, and its capacity is
    // unbounded. Without this the pin below could pass on a sink that simply
    // never got far enough to fill.
    assert_eq!(sink.writes, 1, "it unwound on its first write");
    assert!(
        !sink.returned_full,
        "and never reported itself full — the two conditions are disjoint here"
    );

    // THE PIN. `refuse()` means "this sink is exhausted": it latches the sink
    // and, on a `BoundedSink`, charges the boundary budget its ENTIRE capacity
    // instead of the bytes written. A sink that unwound is not exhausted, it is
    // BROKEN — the opposite diagnosis, which is why the bridge tracks `full`
    // and `panicked` separately in the first place. Charging it as exhaustion
    // spends a budget nobody used and presents a broken caller sink to the
    // carrier as an arena too small. The in-process `walk_inline` agrees: its
    // `CaptureUnwound` arm charges `sink.consumed()` and never calls `refuse`.
    assert_eq!(
        sink.refuse_calls, 0,
        "a panicked sink must not be latched as exhausted"
    );

    // And the diagnosis still names the panic rather than the buffer.
    let text = err.to_string();
    assert!(
        text.contains("panicked"),
        "a broken sink and a small buffer are opposite diagnoses: {text}"
    );
}

#[test]
#[serial]
fn a_sink_that_genuinely_filled_is_still_latched() {
    // THE DISCRIMINATION CONTROL, and the reason the latch is narrowed rather
    // than deleted: the same exporter, the same -6, the same code path —
    // only the sink's condition differs. This one really is exhausted, so it
    // MUST be latched, or a refusal that the trampoline observed would leave
    // the sink reporting its bytes-written and hand the next node a budget this
    // one already spent.
    let (_runtime, probe, _seen) = built_probe("latchfull");

    // Four bytes cannot hold the leading `u64`, so the very first write fills.
    let mut sink = LatchSpySink::bounded(4);
    probe
        .lock()
        .expect("probe")
        .capture_state(&mut sink)
        .expect_err("a 4-byte sink cannot take this node's state");

    assert!(sink.returned_full, "the sink really did fill");
    assert_eq!(sink.writes, 1, "and did so on its first write");
    assert!(
        sink.refuse_calls >= 1,
        "an exhausted sink must still be latched"
    );
}

#[test]
#[serial]
fn a_conforming_exporter_still_maps_a_refused_sink_onto_the_buffer_too_small_arm() {
    // THE INVERSE CONTROL. The same fixture, the same too-small sink, the only
    // difference being that this exporter honours the refusal and reports -6.
    // That path must be untouched: it is a retry-with-a-bigger-buffer, not a
    // broken node and not a broken exporter.
    let _mode = ModeGuard::set("conforming");
    let entry = init_liar();

    let mut sink = RecordingSink::new(8);
    let err = entry
        .capture_state(&mut sink)
        .expect_err("8 bytes cannot hold 24");

    assert_eq!(
        sink.offers,
        vec![(8, true), (12, false)],
        "a conforming exporter STOPS at the first refusal: {:?}",
        sink.offers
    );
    let text = err.to_string();
    assert!(
        text.contains("its buffer is too small"),
        "the conforming arm blames the bound: {text}"
    );
    assert!(
        !text.contains("exporter is BROKEN"),
        "and must NOT accuse a conforming exporter: {text}"
    );
    assert!(sink.refused, "the caller's sink is left refused");
}

#[test]
#[serial]
fn a_capture_that_fits_still_succeeds_byte_identically_for_the_same_exporter() {
    // THE ANTI-TAUTOLOGY CONTROL. Same fixture, same `liar` mode — the only
    // change is a sink big enough that nothing is ever refused. Nothing was
    // refused, so nothing may be refused: the capture succeeds and the bytes
    // are exactly the hand-built payload.
    let _mode = ModeGuard::set("liar");
    let mut entry = init_liar();

    let mut sink = RecordingSink::new(64);
    entry
        .capture_state(&mut sink)
        .expect("a capture nothing refused must succeed");
    assert_eq!(sink.accepted, liar_payload(0));
    assert_eq!(sink.offers, vec![(8, true), (12, true), (4, true)]);
    assert!(!sink.refused);

    // And the round trip closes on the hand oracle at BOTH ends: a hand-built
    // payload goes in through the restore FFI, and the bytes that come back out
    // are compared against a hand-built expectation, never against themselves.
    entry
        .restore_state(&liar_payload(4242))
        .expect("the hand-built payload restores");
    let mut after = RecordingSink::new(64);
    entry.capture_state(&mut after).expect("re-capture");
    assert_eq!(after.accepted, liar_payload(4242));

    // A TRUNCATED payload — exactly what accepting the refused capture above
    // would have recorded — is refused by the restore rather than decoded as a
    // prefix. This is the harm the capture-side pin prevents, stated at the
    // other end of the round trip.
    let truncated = liar_payload(4242)[..8].to_vec();
    entry
        .restore_state(&truncated)
        .expect_err("a truncated anchor must not restore");
}

#[test]
#[serial]
fn a_hint_driven_refusal_latches_the_hosts_own_sink_so_its_prefix_is_never_charged_as_accepted() {
    // The hint-driven shape: a hash-like container consults `remaining_hint` and refuses
    // BEFORE writing anything, so the host's sink is never told. Without the
    // host latching it itself, `BoundedSink::refused()` stays clear and
    // `consumed()` reports the bytes written — usually ZERO — so the boundary
    // walk would hand the SAME budget to the next node, breaking the
    // at-most-one-node-per-boundary charge (`BoundedSink`'s own contract).
    //
    // `BoundedSink` is the oracle here rather than the recording sink because
    // it is the production type that carries the charging rule.
    let _mode = ModeGuard::set("hint_refuse");
    let entry = init_liar();

    let mut arena = [0u8; 16]; // < the fixture's 24-byte payload
    let mut sink = BoundedSink::new(&mut arena);
    let err = entry
        .capture_state(&mut sink)
        .expect_err("16 bytes cannot hold 24");

    assert_eq!(
        sink.len(),
        0,
        "the fixture refused on the HINT, so it never called the sink"
    );
    assert!(
        sink.refused(),
        "the host must latch its own sink: nothing else can, and an unlatched \
         sink hands the next node a budget this one already spent"
    );
    assert_eq!(
        sink.consumed(),
        sink.capacity(),
        "a refused attempt is charged its whole granted capacity"
    );
    assert!(
        err.to_string().contains("its buffer is too small"),
        "the bound, not a broken node: {err}"
    );
}

#[test]
#[serial]
fn an_encoder_error_does_not_latch_the_hosts_sink_because_the_sink_is_not_at_fault() {
    // The other side of the latch rule. `-5` says the NODE's encoder failed
    // while the host's sink was perfectly healthy and had room, so the sink must
    // NOT be latched and must be charged only what it actually took — which is
    // exactly what the in-process `walk_inline` does for its `EncoderError` arm
    // (`used += sink.consumed()` with `refused` clear). Latching everything that
    // fails would be simpler and would diverge: the same node, captured
    // in-process and through the wall, would charge the shared boundary budget
    // differently.
    let _mode = ModeGuard::set("encoder_error");
    let entry = init_liar();

    let mut arena = [0u8; 64]; // ample: nothing here is a bound problem
    let mut sink = BoundedSink::new(&mut arena);
    let err = entry
        .capture_state(&mut sink)
        .expect_err("the node's own encoder failed");

    assert_eq!(sink.len(), 8, "the first chunk was accepted");
    assert!(
        !sink.refused(),
        "a healthy sink must not be latched by the NODE's failure"
    );
    assert_eq!(
        sink.consumed(),
        8,
        "and is charged only the bytes it actually took, not its whole capacity"
    );
    let text = err.to_string();
    assert!(
        text.contains("could not encode this node's state"),
        "blames the node: {text}"
    );
    assert!(
        !text.contains("its buffer is too small"),
        "and NOT the bound: {text}"
    );
}

// ===========================================================================
// THE LOAD-TIME SHAPE REFUSAL (the exporter's own reason must not be lost —
// nor served against something else)
// ===========================================================================

/// Panic-safe process-env switch for one named variable.
///
/// `ModeGuard` above is hard-wired to `STATE_CAPTURE_MODE`; the load-time
/// arms below drive two OTHER switches, and the fixture reads all three
/// independently so a test can set exactly the one it means.
struct EnvGuard(&'static str);

impl EnvGuard {
    fn set(key: &'static str, value: &str) -> Self {
        std::env::set_var(key, value);
        Self(key)
    }
}

impl Drop for EnvGuard {
    fn drop(&mut self) {
        std::env::remove_var(self.0);
    }
}

/// The exact string the fixture leaves in its error slot when its shape export
/// refuses. Spelled out by hand rather than imported: a cdylib is not a
/// linkable dependency of this test, so the oracle has to be independent of the
/// fixture's own constant, which is what makes it an oracle.
const SHAPE_REFUSAL_DETAIL: &str = "liar: state_shape refused — schema registry unavailable";

#[test]
#[serial]
#[tracing_test::traced_test]
fn a_refused_shape_export_reports_the_cdylibs_own_account_of_why() {
    // The exporter refuses to answer for its shape, having said WHY in its
    // error slot. The host reads the shape exactly once, at load, and then
    // switches state off for this node — so this is the only moment that
    // message can ever be told.
    let _shape = EnvGuard::set("STATE_SHAPE_MODE", "fail");
    let entry = DylibNodeEntry::load(&liar_cdylib())
        .expect("a cdylib whose shape export refuses must still LOAD");

    // The capability is off — unchanged, and asserted so the log assertion
    // below cannot be read as testing a node that still has state.
    assert_eq!(
        entry.state_shape(),
        None,
        "a refused shape takes the capability away entirely"
    );

    // Without this the operator sees only `code = -7`, and -7 is not in the
    // FFI's documented code table — so the log would name a number that
    // explains nothing while the sentence that did explain it was thrown away.
    assert!(
        logs_contain(SHAPE_REFUSAL_DETAIL),
        "the shape-failure log must carry the cdylib's own account of the refusal"
    );
}

#[test]
#[serial]
fn a_refused_shape_export_leaves_nothing_behind_to_explain_the_next_failure() {
    // THE STALENESS, and its own arm because it is a different claim from the
    // one above, one that only this arm catches. `LAST_ERROR` is a per-cdylib
    // slot that persists until something TAKES it, and every later failure path
    // reports `take_last_error().unwrap_or_else(|| "…no detail provided")`. So
    // a message left at load is served as the cause of the NEXT failure that
    // sets none of its own — a load-time shape complaint reported against an
    // unrelated tick, seconds or hours later, on a node whose state capability
    // was switched off so long ago nothing will connect the two.
    //
    // Driven with a tick that fails WITHOUT setting a message, which is the
    // ordinary raw-FFI shape (a bare return code — `cerulion_node_shutdown` in
    // the same fixture does it), not a contrived one.
    let _shape = EnvGuard::set("STATE_SHAPE_MODE", "fail");
    let mut entry = DylibNodeEntry::load(&liar_cdylib()).expect("the cdylib loads");
    entry
        .init(cerulion_core::graph::node::NodeContext::for_tests(
            IndexMap::new(),
            IndexMap::new(),
        ))
        .expect("the fixture inits");

    let _tick = EnvGuard::set("STATE_TICK_MODE", "fail_silent");
    let text = entry
        .tick()
        .expect_err("the tick was told to fail")
        .to_string();
    assert!(
        !text.contains(SHAPE_REFUSAL_DETAIL),
        "the tick failure must NOT be explained by the load-time shape refusal: {text}"
    );
    assert!(
        text.contains("cerulion_node_tick returned 9") && text.contains("no detail provided"),
        "it reports its own condition and admits it has no detail: {text}"
    );
}

#[test]
#[serial]
#[tracing_test::traced_test]
fn a_healthy_shape_export_logs_no_refusal_and_leaves_the_error_slot_alone() {
    // The ANTI-TAUTOLOGY control. Without it the arm above would pass against a
    // host that logged the refusal sentence unconditionally, or that drained
    // the slot on every load whether or not anything had been put in it.
    let mut entry = DylibNodeEntry::load(&liar_cdylib()).expect("the liar cdylib loads");
    assert_eq!(
        entry.state_shape(),
        Some(0x1053_D600_5A1E_0001),
        "the hand-written shape constant, spelled out"
    );
    assert!(
        !logs_contain("cerulion_node_state_shape failed"),
        "a healthy shape export must produce no failure log at all"
    );

    // And a failure AFTER a clean load still reports its own condition — the
    // same assertion as (c) above, on the branch where nothing was ever left
    // behind, so "no stale message" cannot be confused with "no message path".
    entry
        .init(cerulion_core::graph::node::NodeContext::for_tests(
            IndexMap::new(),
            IndexMap::new(),
        ))
        .expect("the fixture inits");
    let _tick = EnvGuard::set("STATE_TICK_MODE", "fail_silent");
    let text = entry
        .tick()
        .expect_err("the tick was told to fail")
        .to_string();
    assert!(
        text.contains("cerulion_node_tick returned 9"),
        "reports its own condition: {text}"
    );
}

// ===========================================================================
// THE PANIC-CONTAINMENT PIN (a broken encoder must not brick the library)
// ===========================================================================

/// The macro cdylib whose hand-written `CerulionState` field impl can be told
/// to panic.
fn panic_cdylib() -> std::path::PathBuf {
    find_cdylib("test_node_state_panic_cdylib")
}

/// Two INDEPENDENT nodes from the one panic fixture, both `init`'d.
///
/// Two, because the blast radius is the whole point: `NODES` is a per-CDYLIB
/// registry, so a panic that unwinds through its guard poisons it for every
/// node the library ever loaded — not just the one that panicked. A one-node
/// harness cannot tell "this capture failed" from "this library is dead".
fn two_panic_nodes() -> (DylibNodeEntry, DylibNodeEntry) {
    let mut a = DylibNodeEntry::load(&panic_cdylib()).expect("the panic cdylib loads");
    let mut b = DylibNodeEntry::load(&panic_cdylib()).expect("the panic cdylib loads twice");
    for entry in [&mut a, &mut b] {
        entry
            .init(cerulion_core::graph::node::NodeContext::for_tests(
                IndexMap::new(),
                IndexMap::new(),
            ))
            .expect("the panic fixture inits");
    }
    (a, b)
}

#[test]
#[serial]
fn a_panicking_state_encoder_fails_its_own_capture_without_poisoning_the_cdylibs_node_registry() {
    let (a, b) = two_panic_nodes();

    // The CONTROL first, so every number below is attributable to the panic
    // rather than to the fixture: with the mode off, both nodes capture the
    // hand-built encoding of `Fragile` — a bare `u64`, value 0.
    let mut sink = VecSink::new();
    a.capture_state(&mut sink).expect("a healthy capture");
    assert_eq!(sink.into_inner(), 0u64.to_le_bytes().to_vec());

    let refusal = {
        let _panic = EnvGuard::set("STATE_PANIC_MODE", "capture");
        let mut sink = VecSink::new();
        let err = a
            .capture_state(&mut sink)
            .expect_err("a panicking encoder cannot report success");
        assert!(
            sink.is_empty(),
            "and nothing was captured — a partial encoding is not an anchor"
        );
        err.to_string()
    };

    // THE PIN, asserted BEFORE the wording below: a message assertion that
    // fires first would shadow this one, and this is the claim that matters. `cer_capture` ran while the export held this cdylib's `NODES`
    // MutexGuard. An unwind through that guard POISONS it, and `NODES` is
    // per-library: from that moment every capture, restore, tick and shutdown
    // of every node loaded from this cdylib fails "NODES mutex poisoned", for
    // the life of the process, with the cause misreported as a tick panic that
    // never happened. So the second node — which never captured
    // anything and was nowhere near the panic — is the witness.
    b.capture_state(&mut VecSink::new())
        .expect("the OTHER node must be untouched by a panic in the first");

    // Only now the wording, which is a separate claim, caught separately:
    // the OUTER `catch_unwind` also returns -4, so a host that reported its
    // generic "panic caught by catch_unwind" would pass every assertion above.
    assert!(
        refusal.contains("encoder panicked"),
        "names what happened, not merely that something did: {refusal}"
    );

    // And the node that panicked is not itself dead: it captures again as soon
    // as its encoder does.
    let mut sink = VecSink::new();
    a.capture_state(&mut sink).expect("the same node recovers");
    assert_eq!(sink.into_inner(), 0u64.to_le_bytes().to_vec());
}

#[test]
#[serial]
fn a_panicking_state_decoder_fails_its_own_restore_without_poisoning_the_cdylibs_node_registry() {
    let (mut a, mut b) = two_panic_nodes();
    // The single captured field encodes as a bare `u64`, so the whole payload
    // for this node is eight bytes — hand-built, per the documented encoding.
    let payload = 42u64.to_le_bytes().to_vec();

    // CONTROL: the restore lands, and is observable through the node's own tick
    // (which publishes `payload.value` and then increments it).
    a.restore_state(&payload).expect("a healthy restore");

    let refusal = {
        let _panic = EnvGuard::set("STATE_PANIC_MODE", "restore");
        a.restore_state(&payload)
            .expect_err("a panicking decoder cannot report success")
            .to_string()
    };

    // The same no-poison pin on the restore half, and again BEFORE the wording: the
    // sibling node, which never restored anything, is the witness.
    b.restore_state(&payload)
        .expect("the OTHER node must be untouched by a panic in the first");

    assert!(
        refusal.contains("decoder panicked"),
        "names what happened, not merely that something did: {refusal}"
    );
    assert!(
        refusal.contains("PARTIALLY restored"),
        "and says the run must fail rather than continue: {refusal}"
    );
    a.restore_state(&payload)
        .expect("and the node that panicked recovers");
}

// ===========================================================================
// THE UNCOVERED NODE AS THE RUNTIME SEES IT
// ===========================================================================

/// One port-less node, so a symbol-less cdylib can be wired into a real graph.
fn uncovered_graph(prefix: &str) -> GraphConfig {
    GraphConfig {
        level_assignments: None,
        network: None,
        process_groups: Default::default(),
        process_group_order: Default::default(),
        multi_publisher_topics: Vec::new(),
        name: None,
        identity: "d6_uncovered".to_string(),
        prefix: prefix.to_string(),
        nodes: vec![NodeDef {
            ros2: None,
            id: "plain".to_string(),
            node_type: "plain".to_string(),
            inputs: vec![],
            outputs: vec![],
        }],
    }
}

#[test]
#[serial]
fn the_runtime_reports_an_uncovered_cdylib_node_under_declared_no_state_rather_than_restoring_it() {
    // The sibling arm above drives `DylibNodeEntry::restore_state` DIRECTLY,
    // which proves the refusal but says nothing about the surface that decides
    // whether a run may proceed: `--strict-state` judges
    // `RestoreReport::declared_no_state`, and that list is built by
    // `GraphRuntime::restore_node_states`, not by the entry. A runtime that
    // stopped populating it would leave the strict gate silently permissive
    // with every direct-refusal assertion still green.
    let entry = DylibNodeEntry::load(&symbol_less_cdylib()).expect("the raw-FFI cdylib loads");
    let mut factories: IndexMap<String, Box<dyn NodeEntry>> = IndexMap::new();
    factories.insert("plain".to_string(), Box::new(entry));
    let runtime = GraphRuntime::build_for_test(
        uncovered_graph(&prefix_for("uncov")),
        factories,
        Arc::new(VirtualClock::new()),
        16,
    )
    .expect("a port-less graph builds");

    // An anchor IS offered for it — the arm is worthless otherwise, since a
    // node with no anchor is skipped before the state question is ever asked.
    let mut anchors = std::collections::BTreeMap::new();
    anchors.insert(
        "plain".to_string(),
        framed(0x1053_D600_5A1E_0001, &hand_payload(1, "x", &[], &[])),
    );

    let report = runtime
        .restore_node_states(&anchors)
        .expect("an uncovered node is REPORTED, never an error that aborts the whole restore");

    assert_eq!(
        report.declared_no_state,
        vec!["plain".to_string()],
        "the uncovered node reaches the surface `--strict-state` judges"
    );
    assert!(
        report.restored.is_empty(),
        "and is NOT counted as restored — that claim would be fabricated state"
    );
    assert!(
        report.anchors_unused.is_empty(),
        "the anchor was matched to a node; it was the NODE that could not take it"
    );

    // The complement, from the same runtime: the strict gate's own input agrees
    // with the report, so the two cannot disagree about one node.
    //
    // `nodes_without_state` is scoped to the EXECUTED set: a
    // node the resumed suffix never ticks is not reported, because nothing
    // reads its state. This node IS executed, so it must appear — and passing
    // the set makes that a stated premise of the arm rather than an assumption.
    let executed: std::collections::BTreeSet<String> =
        std::iter::once("plain".to_string()).collect();
    assert_eq!(
        runtime.nodes_without_state(&executed).expect("readable"),
        vec!["plain".to_string()],
    );
}

// ===========================================================================
// — the CARRIER symbols across the same wall
// ===========================================================================

#[test]
#[serial]
fn a_macro_cdylib_reports_its_own_inline_safety_rather_than_the_hosts_safe_default() {
    // Without `cerulion_node_inline_safe` every cdylib node inherits the host's
    // safe default (`false`), so the whole INLINE carrier is dead code on a real
    // graph — every node takes `fork(2)` at every cadence. And the failure is
    // SILENT: the anchors still appear, with byte-identical contents, because
    // both carriers run the same generated encoder. Nothing in a bag, a log or a
    // test of the capture ITSELF can see the difference.
    //
    // The fixture is plain data — four owned fields, no lock anywhere in the
    // state graph — so its `INLINE_SAFE` is TRUE, and reading `false` here is
    // exactly the silent degradation above.
    let (_runtime, probe, _seen) = built_probe("insafe");
    assert!(
        probe.lock().expect("probe").inline_safe(),
        "a plain-data macro cdylib must report itself inline-safe; `false` here is the \
         host's default showing through, which costs a fork(2) per anchor and looks \
         identical in the bag"
    );
}

#[test]
#[serial]
fn a_macro_cdylib_answers_the_pre_fork_lock_probe_over_its_own_state() {
    // The pre-fork lock probe, across the wall. The node's state graph holds no lock, so it
    // is quiescent — and the answer must come from the CDYLIB rather than from
    // the host's default, which happens to agree. The disagreeing arm is the
    // uninitialized one below, which no default can produce.
    let (_runtime, probe, _seen) = built_probe("probe");
    assert!(
        probe.lock().expect("probe").cer_probe(),
        "a lock-free node's state graph is quiescent at a boundary"
    );
}

#[test]
#[serial]
fn an_uninitialized_cdylib_is_not_quiescent_because_nothing_can_show_that_it_is() {
    // THE arm that separates a real answer from the trait's default. A node that
    // has not been `init`'d has no handle, so the probe cannot be asked about any
    // instance — and the host must say NOT QUIESCENT rather than fall back to the
    // optimistic default.
    //
    // The cost of that answer is one skipped anchor. The cost of the other is a
    // child that inherits a held lock: a fork child has exactly one thread, so
    // nothing can ever release it, and it wedges until the watchdog SIGKILLs it
    // five seconds later — reported as a stalled encoder that never ran.
    let entry = DylibNodeEntry::load(&state_cdylib()).expect("state cdylib loads");
    assert!(
        entry.inline_safe(),
        "the TYPE-level const is answerable without an instance, and must be"
    );
    assert!(
        !entry.cer_probe(),
        "the INSTANCE-level probe is not, and an unanswerable probe must read \
         NOT-quiescent"
    );
}

#[test]
#[serial]
fn a_symbol_less_cdylib_forks_and_is_believed_quiescent() {
    // BACK-COMPAT, and the two defaults pull in opposite directions on purpose.
    //
    // `inline_safe` defaults FALSE: a cdylib that has not proved it can be
    // encoded on the node thread must not claim it, and being wrong costs a
    // `fork(2)` rather than a wrong capture.
    //
    // `cer_probe` defaults TRUE: such a node declares no state graph at all, so
    // there is nothing for a probe to be true OF — and refusing on its behalf
    // would skip every anchor of every OTHER node in the process, for the life of
    // the run, on behalf of a node that contributes none. The residual is the
    // design's documented one: it is covered by the child's progress watchdog
    // instead.
    let entry = DylibNodeEntry::load(&symbol_less_cdylib()).expect("raw-FFI cdylib loads");
    assert!(
        !entry.inline_safe(),
        "a cdylib that exports no inline-safety claim must not be credited with one"
    );
    assert!(
        entry.cer_probe(),
        "and one that declares no state graph must not veto the whole anchor"
    );
    // ANTI-TAUTOLOGY: it really is the symbol-less fixture, not a load that
    // quietly failed into defaults.
    assert!(
        entry.state_shape().is_none(),
        "the raw-FFI fixture declares no state either — if it did, this is the \
         wrong library"
    );
}
