// SPDX-License-Identifier: AGPL-3.0-only
//! Build script for native_ros2_messages.
//!
//! Scans msg/ directory, parses .msg files, and generates Rust code.
//!
//! All collections are BTreeMap/sorted so the generated code is
//! byte-identical across builds — codegen output ordering must be
//! deterministic (Principle #7).

use cerulion_core::codegen::{
    generate_schema, parse_rosmsg, resolve_fixed_nested, FieldType, MessageSchema,
};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let msg_dir = Path::new("msg");

    // Collect all .msg files by package
    let mut packages: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    if msg_dir.exists() {
        collect_msg_files(msg_dir, &mut packages);
    }

    // Emit the embedded built-in message registry — the exact
    // vendored .msg text frozen at build time. `cerulion_cli_engine`'s
    // schema introspection parses THIS text (not the msg/ tree at CLI
    // runtime), so a resolved layout can never skew from the generated
    // types this crate compiled. Keyed by (package, message) through a
    // BTreeMap for deterministic sorted emission (Principle #7). Raw
    // content only — the resolver re-parses it, keeping the frozen text
    // the single source.
    {
        let mut registry: BTreeMap<(&str, &str), &str> = BTreeMap::new();
        for (package, messages) in &packages {
            for (msg_name, msg_content) in messages {
                registry.insert((package.as_str(), msg_name.as_str()), msg_content.as_str());
            }
        }

        let mut registry_code = String::new();
        registry_code.push_str("// Generated built-in ROS2 message registry.\n");
        registry_code.push_str("// DO NOT EDIT - generated by native_ros2_messages build.rs\n\n");
        registry_code.push_str("/// Embedded built-in ROS 2 message registry.\n");
        registry_code.push_str("///\n");
        registry_code.push_str("/// One `(package, message_name, raw_msg_text)` tuple per\n");
        registry_code.push_str("/// vendored `.msg`, in ascending `(package, message_name)`\n");
        registry_code.push_str("/// order. `raw_msg_text` is the exact source frozen at build\n");
        registry_code.push_str("/// time (the same text this script parsed to generate the\n");
        registry_code.push_str("/// `ShmMessage` types), so schema introspection resolves wire\n");
        registry_code.push_str("/// layouts that can never skew from the generated types.\n");
        registry_code.push_str("pub static BUILTIN_MSGS: &[(&str, &str, &str)] = &[\n");
        for ((package, msg_name), msg_content) in &registry {
            registry_code.push_str(&format!(
                "    ({package:?}, {msg_name:?}, {msg_content:?}),\n"
            ));
        }
        registry_code.push_str("];\n");

        let registry_file = format!("{}/msg_registry.rs", out_dir);
        fs::write(&registry_file, &registry_code).expect("Failed to write msg_registry.rs");
    }

    // First pass: parse all schemas. The package name is part of
    // the schema-hash input ("pkg/Name"), so identically named messages in
    // different packages get distinct wire hashes.
    let mut all_schemas: BTreeMap<String, Vec<MessageSchema>> = BTreeMap::new();
    for (package, messages) in &packages {
        let mut pkg_schemas = Vec::new();
        for (msg_name, msg_content) in messages {
            match parse_rosmsg(msg_content, msg_name, Some(package)) {
                Ok(schema) => pkg_schemas.push(schema),
                Err(e) => {
                    // Vendored .msg files are repo-controlled inputs — a
                    // parse failure is always a bug, and silently skipping
                    // the message would let REFERENCES to it silently
                    // degrade (or rebind through the bare-name fallback).
                    // Fail the build.
                    panic!("failed to parse {}/{}.msg: {}", package, msg_name, e);
                }
            }
        }
        pkg_schemas.sort_by(|a, b| a.name.cmp(&b.name));
        all_schemas.insert(package.clone(), pkg_schemas);
    }

    // Nested-resolution prerequisite: resolve nested-reference fixedness across
    // the whole schema set so recursively-fixed nested types (Pose, Twist,
    // Transform, …) inline into the parent's fixed section and stay
    // zero-copy. Operates on a flat view; schemas carry their package.
    {
        let mut flat: Vec<MessageSchema> = Vec::new();
        for schemas in all_schemas.values() {
            flat.extend(schemas.iter().cloned());
        }
        let warnings = resolve_fixed_nested(&mut flat);
        if !warnings.is_empty() {
            // For the vendored ROS2 set, every nested reference MUST
            // resolve cleanly: an unresolved/ambiguous/cross-package-bare
            // reference silently changes the parent's WIRE LAYOUT while
            // the (FQN-keyed but layout-blind) schema hash stays the same — a wire-skew
            // hazard, not a cosmetic issue. Fail the build rather than
            // warn.
            for warning in &warnings {
                println!("cargo:warning=nested resolution: {}", warning);
            }
            panic!(
                "nested-schema resolution produced {} warning(s) — every reference in the \
                 vendored .msg set must resolve cleanly (see cargo warnings above)",
                warnings.len()
            );
        }
        // Redistribute resolved schemas back into their packages
        // (same order as flattening: BTreeMap iteration is stable).
        let mut iter = flat.into_iter();
        for schemas in all_schemas.values_mut() {
            for slot in schemas.iter_mut() {
                *slot = iter.next().expect("resolver preserved schema count");
            }
        }
    }

    // Map of bare message name -> package, for resolving UNQUALIFIED
    // cross-package references. Qualified references (pkg/Msg) carry their
    // package on the FieldType::Nested node and never consult this map.
    // Bare-name collisions across packages are reported loudly — an
    // unqualified reference to a collided name is ambiguous.
    let mut msg_to_package: BTreeMap<String, String> = BTreeMap::new();
    let mut collided: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (package, schemas) in &all_schemas {
        for schema in schemas {
            if let Some(prev) = msg_to_package.insert(schema.name.clone(), package.clone()) {
                collided
                    .entry(schema.name.clone())
                    .or_insert_with(|| vec![prev])
                    .push(package.clone());
            }
        }
    }
    for (name, pkgs) in &collided {
        println!(
            "cargo:warning=message name '{}' is defined in multiple packages ({}); \
             unqualified references to it are ambiguous — qualify as pkg/{} in .msg files",
            name,
            pkgs.join(", "),
            name
        );
    }

    // rosidl's bare-`Header` special case binds iff std_msgs/Header
    // exists — computed from the QUALIFIED schema set, exactly like
    // resolve.rs::lookup's check (a bare
    // `msg_to_package.contains_key("Header")` approximation diverges
    // when Header exists only in a non-std_msgs package).
    let std_msgs_has_header = all_schemas
        .get("std_msgs")
        .is_some_and(|schemas| schemas.iter().any(|s| s.name == "Header"));

    // Generate code for each package
    let mut all_modules = Vec::new();

    for (package, schemas) in &all_schemas {
        let mut package_code = String::new();
        package_code.push_str(&format!("//! {} message types.\n", package));
        package_code.push_str("//!\n");
        package_code.push_str("//! Generated at build time from `.msg` files. Do not edit the\n");
        package_code.push_str("//! generated source: it is rewritten on every build.\n");
        package_code.push_str("//!\n");
        package_code.push_str(&format!(
            "//! Source: the `msg/{}/` directory of the `native_ros2_messages` crate.\n\n",
            package
        ));
        package_code.push_str("#![allow(dead_code, unused_imports)]\n\n");

        // Add imports for cross-package dependencies
        let deps = collect_package_deps(schemas, &msg_to_package, package, std_msgs_has_header);
        for dep in &deps {
            package_code.push_str(&format!("use crate::{}::*;\n", dep));
        }
        if !deps.is_empty() {
            package_code.push('\n');
        }

        for schema in schemas {
            let code = generate_schema(schema);
            package_code.push_str(&format!("// === {} ===\n", schema.name));
            package_code.push_str(&code);
            package_code.push('\n');
        }

        // Write package module
        let package_file = format!("{}/{}.rs", out_dir, package);
        fs::write(&package_file, &package_code).expect("Failed to write package file");

        all_modules.push(package.clone());
        // Routine status goes to the build LOG only (visible with -vv) —
        // `cargo:warning` is reserved for actual problems so real
        // diagnostics don't drown in 16 lines of routine noise.
        println!("generated: {} ({} messages)", package, schemas.len());
    }

    // Generate ros2_msgs.rs that re-exports all packages
    let mut ros2_msgs = String::new();
    ros2_msgs.push_str("// Generated ROS2 message types.\n");
    ros2_msgs.push_str("// DO NOT EDIT - generated by native_ros2_messages build.rs\n\n");

    for module in &all_modules {
        ros2_msgs.push_str(&format!(
            "#[path = \"{out_dir}/{module}.rs\"]\npub mod {module};\n"
        ));
    }

    let ros2_msgs_file = format!("{}/ros2_msgs.rs", out_dir);
    fs::write(&ros2_msgs_file, &ros2_msgs).expect("Failed to write ros2_msgs.rs");

    // Tell Cargo to rerun if msg files change
    println!("cargo:rerun-if-changed=msg/");
}

/// Collect all packages that this package depends on.
fn collect_package_deps(
    schemas: &[MessageSchema],
    msg_to_package: &BTreeMap<String, String>,
    current_package: &str,
    std_msgs_has_header: bool,
) -> Vec<String> {
    let mut deps = std::collections::BTreeSet::new();

    for schema in schemas {
        for field in &schema.fields {
            collect_field_deps(
                &field.field_type,
                schemas,
                msg_to_package,
                current_package,
                std_msgs_has_header,
                &mut deps,
            );
        }
    }

    deps.into_iter().collect()
}

fn collect_field_deps(
    ft: &FieldType,
    current_schemas: &[MessageSchema],
    msg_to_package: &BTreeMap<String, String>,
    current_package: &str,
    std_msgs_has_header: bool,
    deps: &mut std::collections::BTreeSet<String>,
) {
    match ft {
        FieldType::Nested {
            schema_name,
            package,
            ..
        } => {
            // Mirror resolve.rs::lookup exactly so the dep graph
            // and the layout resolution never disagree about which package
            // an unqualified name binds to:
            // qualified > same-package (checked against THIS package's own
            // schema set, not the lossy last-wins global map) > bare
            // `Header` → std_msgs (rosidl legacy special case) > global
            // bare-name fallback.
            let same_package = current_schemas.iter().any(|s| &s.name == schema_name);
            let resolved = package.as_deref().or_else(|| {
                if same_package {
                    Some(current_package)
                } else if schema_name == "Header" && std_msgs_has_header {
                    // Bind iff std_msgs/Header EXISTS in the schema set —
                    // the exact condition resolve.rs::lookup checks.
                    Some("std_msgs")
                } else {
                    msg_to_package.get(schema_name).map(|s| s.as_str())
                }
            });
            if let Some(pkg) = resolved {
                if pkg != current_package {
                    deps.insert(pkg.to_string());
                }
            }
        }
        FieldType::FixedArray { element_type, .. } | FieldType::DynamicArray { element_type } => {
            collect_field_deps(
                element_type,
                current_schemas,
                msg_to_package,
                current_package,
                std_msgs_has_header,
                deps,
            );
        }
        _ => {}
    }
}

fn collect_msg_files(dir: &Path, packages: &mut BTreeMap<String, Vec<(String, String)>>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                // This is a package directory
                let package_name = path.file_name().unwrap().to_string_lossy().to_string();
                let package_name = sanitize_package_name(&package_name);

                if let Ok(msg_entries) = fs::read_dir(&path) {
                    for msg_entry in msg_entries.flatten() {
                        let msg_path = msg_entry.path();
                        if msg_path.extension().is_some_and(|e| e == "msg") {
                            let msg_name =
                                msg_path.file_stem().unwrap().to_string_lossy().to_string();

                            // Vendored inputs: an unreadable/non-UTF-8 .msg
                            // must fail the build, not silently vanish.
                            let content = fs::read_to_string(&msg_path).unwrap_or_else(|e| {
                                panic!("failed to read {}: {}", msg_path.display(), e)
                            });
                            packages
                                .entry(package_name.clone())
                                .or_default()
                                .push((msg_name, content));
                        }
                    }
                }
            }
        }
    }
}

fn sanitize_package_name(name: &str) -> String {
    // Convert package names to valid Rust identifiers
    name.replace('-', "_")
}
