// SPDX-License-Identifier: AGPL-3.0-only
//! The rustc that compiled THIS copy of `cerulion_core`.
//!
//! `NodeContext` crosses the cdylib `init()` FFI boundary as a raw `Box`, and
//! the cdylib links its OWN copy of `cerulion_core`, so a `repr(Rust)` type
//! reachable through it (`CerulionSubscriber.frozen: Option<FrozenSlot>` is
//! the one that breaks) is laid out however THAT PARTICULAR rustc's
//! niche-filling pass decides. `CERULION_ABI_VERSION` proves struct sizes and
//! offsets agree between host and cdylib, but rustc 1.97.0 changed the `None`
//! bit pattern for a niche-holding 4-variant `Option` WITHOUT moving any
//! offset, a divergence the ABI version and the `abi_layout` size and offset
//! pins cannot see. [`crate::graph::node::DylibNodeEntry::load`] compares this
//! fingerprint across the FFI boundary to close that hole: a host and a cdylib
//! compiled by different rustc releases are refused at load, loudly, before
//! either side's `Option<FrozenSlot>` is ever read.

use std::ffi::CString;
use std::os::raw::c_char;
use std::sync::OnceLock;

/// The rustc release and commit hash that compiled this copy of
/// `cerulion_core`, for example
/// `"1.97.1 (8bab26f4f68e0e26f0bb7960be334d5b520ea452)"`: `rustc -vV`'s
/// `commit-hash:` field verbatim, the full 40-character SHA-1, never truncated
/// to git's short form. Captured by `build.rs` from `rustc -vV` at compile
/// time, so it is always the compiler cargo actually invoked (it honors
/// `rustup` overrides), never merely the first `rustc` on `$PATH`.
///
/// Two known gaps, both load-bearing for how the comparison in
/// [`crate::graph::node::DylibNodeEntry::load`] can fail to help even when it
/// correctly refuses:
/// - A rustc with no commit hash to report (a Homebrew or Linux distribution
///   package, which print `unknown`) never matches a `rustup`-installed build
///   of the very same release. Rebuilding through `rustup`, the guard's own
///   remedy, genuinely fixes this, since it replaces the hash-less compiler
///   rather than merely reinstalling the same one.
/// - For a nightly or beta host, [`RUSTC_RELEASE`] (for example
///   `"1.99.0-nightly"`) is not a valid `rustup toolchain install` argument on
///   its own: nightly builds are named by DATE (`nightly-2026-09-01`), which
///   this static does not capture. The guard still refuses correctly; only the
///   suggested `rustup toolchain install <release>` remedy does not apply as
///   written on a nightly or beta host.
///
/// Compared across the cdylib FFI boundary by
/// [`crate::graph::node::DylibNodeEntry::load`]; see the module docs above for
/// why the ABI version alone cannot catch a toolchain skew.
pub static RUSTC_FINGERPRINT: &str = env!("CERULION_RUSTC_FINGERPRINT");

/// Just the `release` field of [`RUSTC_FINGERPRINT`] (for example `"1.97.1"`,
/// without the parenthesized commit hash): the exact string a
/// `rustup toolchain install <this>` or `RUSTUP_TOOLCHAIN=<this>` command
/// names.
pub static RUSTC_RELEASE: &str = env!("CERULION_RUSTC_RELEASE");

/// Lazily-built, process-lifetime `CString` backing
/// [`rustc_fingerprint_cstr`]'s returned pointer.
static RUSTC_FINGERPRINT_CSTRING: OnceLock<CString> = OnceLock::new();

/// A pointer to a static, null-terminated C string holding
/// [`RUSTC_FINGERPRINT`]: the body of the `cerulion_rustc_fingerprint()` FFI
/// export every cdylib node crate must define at ABI 22 and later
/// (macro-generated by `cerulion_macros::codegen`; hand-rolled by the
/// `cerulion node create --raw-ffi` template and every hand-written test
/// fixture). Mirrors the `cerulion_node_info()` static-bytes convention: the
/// pointer is valid for the lifetime of the process, no allocation happens
/// after the first call, and the cdylib never frees it.
///
/// # Panics
///
/// If `RUSTC_FINGERPRINT` somehow embedded a NUL byte, which `rustc -vV`'s
/// single-line `release:` and `commit-hash:` fields never do in practice
/// (`build.rs` takes each field off one line of that output, so an embedded
/// NUL would have to appear inside a compiler version string).
pub fn rustc_fingerprint_cstr() -> *const c_char {
    RUSTC_FINGERPRINT_CSTRING
        .get_or_init(|| {
            CString::new(RUSTC_FINGERPRINT)
                .expect("RUSTC_FINGERPRINT unexpectedly contained a NUL byte")
        })
        .as_ptr()
}
