std_msgs/Header header
float64[] traction_wheels_position  # positions of traction wheels if the robot is controlled by position
float64[] traction_wheels_velocity  # velocities of traction wheels if the robot is controlled by velocity
float64[] steer_positions           # positions of steering joints
float64[] traction_command          # values commanded to traction joints
float64[] steering_angle_command    # values commanded to steering joints
