[package]
name = "brightness_meter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
cdylib = []
default = ["cdylib"]

[dependencies]
cerulion_core = { workspace = true }
native_ros2_messages = { workspace = true }

[dev-dependencies]
cerulion_core = { workspace = true, features = ["test-helpers"] }
